### ISSUE TITLE
Unable to display Chinese

### ISSUE THREAD

**Issue by hjlo** [GraphiteEditor/Graphite#1086]
svg cannot display Chinese（Text Tool）

**Comment by 0HyperCube** [comment]
Hello, thanks for reporting this issue @hjlo.

The default font [Merriweather](https://fonts.google.com/specimen/Merriweather?preview.text=%E4%BD%A0%E5%A5%BD%E4%B8%96%E7%95%8C&preview.text_type=custom) does not support Simplified Chinese glyphs. Other fonts, such as [Noto Serif SC](https://fonts.google.com/noto/specimen/Noto+Serif+SC), do contain these glyphs. The font can be changed in the properties panel in the font section.

To avoid not rendering glyphs, we need a list of fonts to fallback on if the glyph does not exist, which could perhaps be specified by the user.  The text tool is unfortunately quite primitive, and we would be grateful if anyone would be interested in contributing code in order to improve it.

**Comment by Keavon** [comment]
Since this works with supported fonts, I'll close this issue for now. Feel free to comment if you encounter any other issues, though! When internationalization becomes a higher priority and we've had a chance to revamp our text editing, we can work towards fallback fonts as 0HyperCube suggested. Thanks for filing the issue!
