### ISSUE TITLE
Using Undo on a Pen path should undo the nodes individually

### ISSUE THREAD

**Issue by MonotoneDevelopment** [GraphiteEditor/Graphite#1323]
It just is really annoying having messed up one part of a node while using Pen and when I instinctively use Undo, the whole path is gone.

**Comment by Keavon** [comment]
You're very right that this is a rather annoying shortcoming for the Pen tool's UX. We have an issue for it here: #971 but last time this came up, there were some subtle architectural limitations that made this harder than it initially seemed to implement which is why it hasn't been completed yet. Hopefully we are able to move past those limitations soon (we're in the process of refactoring a lot of the code and systems to provide a more stable base) and then implement this without the aforementioned difficulty. Or someone could work past the existing limitation with some extra effort.

Closing this since it's a duplicate but feel free to continue a discussion in that issue (or here if relevant).
