### ISSUE TITLE
Feature: Eraser tool

### ISSUE THREAD

**Issue by wez470** [GraphiteEditor/Graphite#1357]
Cool project!

I'm not sure how open project is to feature requests as issues, but I noticed there didn't seem to be an eraser tool at the moment (or at least I couldn't find it). I think it would be really nice to have this.

**Comment by Keavon** [comment]
If you're using the latest development version at https://dev.graphite.rs, the Brush tool has an erase mode. This can be used on the brush strokes you've already drawn, or it can be used on a bitmap image if you make the node setup like this:

![image](https://github.com/GraphiteEditor/Graphite/assets/4388688/0b801c7f-dd1d-4832-9c4a-c2ee9ee68a10)

That's pretty clunky right now because we haven't built the tooling surrounding the automated management of the node graph to be very robust or systematic. But it's a start.

I'm going to close this since it's technically implemented in a basic way, but if you want to point out other use cases not covered by this and explain what those are, I can reopen it to make this issue refer to those cases specifically. Thanks for the issue, and indeed we're always excited to have issues filed for problems and feature requests.
