### ISSUE TITLE
Remove adaptive resolution system

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1514]
The adaptive resolution system is where nodes are passed a `Footprint`. However this doesn't work because it is impossible to know the transform beforehand due the pivot being based on the size of the layer.

The footprint will always be incorrect in cases where there is a transform node with a scale if the bounding box is not 1x1.

This is because the transform for the footprint in the transform node is computed using the pivot transform assuming that the bounding box of the layer is 1x1. We then call the upstream nodes with this incorrect footprint. Then we get the actual data and compute the real pivot based on the bounding box of the layer.

Due to the fact that the Footprint system doesn't work and adds significant complexity to the code, I believe that it should be removed. Unblocks #1498.

Thoughts @TrueDoctor @Keavon?

**Comment by Keavon** [comment]
I'm in agreement (although if it makes sense to do so, perhaps just disabling it rather than removing its code unless that is likely to be a maintenance burden where rewriting it later down the line is easier than the effort of us working around it then restoring it later on). As far as our roadmap is concerned, we don't really have any need for adaptive resolution whatsoever until we have a reasonably advanced level of raster editing capabilities which is probably a year away, if not a bit longer. And indeed the system is causing some serious headaches for both users and us developers.

But let's schedule a call together with @TrueDoctor and talk through this. He has told me it'll be a requirement for GPU execution, but it's unclear to me why that must necessarily be the case.

**Comment by 0HyperCube** [comment]
Closed in favour of #1530 - seeing as you advocated for this system @Keavon I've assigned you the issue of designing and implementing it for all of the tools - however I am happy to help with debugging.
