### ISSUE TITLE
Further customisation of snapping

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1705]
Currently the user can only choose to toggle snapping to bounding boxes and snapping to geometry.
![current snap settings](https://github.com/GraphiteEditor/Graphite/assets/78500760/762165bf-3f6f-40c2-b071-784f34a19be6)

This should be expanded to allow users to for example ignore snapping to bounding box centres but still snap to corners. State to enable more fine grained snapping is already implemented as part of the `BoundsSnapping` and `NodeSnapping` structs. The `"Snap customization settings"` popup is declared in `document_message_handler.rs` and the snapping state is stored in `misc.rs`.

**Comment by 0HyperCube** [comment]
@shyamjayakannan I'm not sure what you mean by a maybe enums. The struct here stores these booleans separately as you can snap to many things at the same time, but if you approach keeps this behaviour then it will be fine.

**Comment by shyamjayakannan** [comment]
@0HyperCube sorry for not being clearer. I mean that maybe we could split `bounding_box_snapping` and `geometry_snapping` further into enums inside which there will be variants for example ignore snapping to bounding box centers but still snap to corners, or snap only to centers, etc

**Comment by shyamjayakannan** [comment]
Would behavior like that in the video below be alright?

https://github.com/GraphiteEditor/Graphite/assets/120047549/8b1cb1da-5310-480f-8823-c8dd5d6f2049

As can be seen in the video, earlier the cursor was snapping to Bounding Box edges, but turning it off removes the snapping behavior.

I have also removed the checkboxes in front of the Bounding boxes and Geometry options that were present earlier because the snapping can be further customized using the `Popover` button

**Comment by shyamjayakannan** [comment]
@Keavon will do. Should I make a separate PR or add commits to #1727?

**Comment by Keavon** [comment]
Separate PRs for separate topics.
