### ISSUE TITLE
Pen tool start position offset on offset artboard

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#1983]
When drawing a new path with the pen tool on an offset artboard (not at the origin), the start point is in the wrong place.

**Comment by 0HyperCube** [comment]
This is also the case with the freehand tool. This was previously fixed just 2 days ago in #1977.

**Comment by Keavon** [comment]
Thanks for finding these regressions for @adamgerhant! I hope he may have time to investigate and fix them.

**Comment by adamgerhant** [comment]
This is because the Artboard no longer transforms its children. I thought this was intended, but the correct solution is for only resizing to not move the children relative to the viewport. This can be achieved by adding a transform node to the graphic group when resizing so that the children move relative to the artboard, but appear to be stationary.
