### ISSUE TITLE
Will there be a way to disable the AI features?

### ISSUE THREAD

**Issue by EzequielBruni** [GraphiteEditor/Graphite#2022]
So I love the idea of Graphite... except for the gen AI features. Will there be a way to disable these features entirely, or at least a way to hide them from the interface?

**Comment by Keavon** [comment]
Those features are currently not implemented, but some leftover code remains in the app, after we broke the prototype implementation about a year ago during some major code overhauls. Once we eventually fix the feature and get it up and running again, it won't appear unless you intentionally seek to use it since intrusive features aren't part of our design philosphy.
