### ISSUE TITLE
Feature: Add a production container image to run it on own server.

### ISSUE THREAD

**Issue by aleleba** [GraphiteEditor/Graphite#2031]
I do not know if there is on the plan, but should be great to have the oportunity to run the project inside a docker container or in podman, should be great to try to run it locally in an easy way.

It should be great to prepare on the CI/DC Pipeline the publishing of a new image on a container repo, so the comunity can run it locally.

Thank you in advance, also I can get some hands on to help you to acomplish this 👍🏼

**Comment by Keavon** [comment]
You can download the static assets for the build from `graphite-self-hosted-build.zip` at <https://github.com/GraphiteEditor/Graphite/releases/tag/latest-stable>. You can serve these static assets from any simple HTTP server, so there's no need for a Docker container. But you'll have to keep checking for updates regularly, so I recommend just using our CDN's hosting of the static assets through https://editor.graphite.rs unless you need to run in an environment without a stable internet connection, in order to benefit from updates when they're available.

**Comment by ecker00** [comment]
My fist go to is looking for Docker image for any project. But you were right, this was super easy to setup!

For other lazy people who arrive here, this is how:

```sh
mkdir -p ./GraphiteEditor
cd ./GraphiteEditor

# Make docker compose
echo 'services:
  webserver:
    image: nginx:latest
    ports:
      - "5656:80"
    volumes:
      - ./app:/usr/share/nginx/html
' > compose.yml

# Make update script
echo '#!/bin/zsh
rm -rf ./app # Delete old version if exist
wget https://github.com/GraphiteEditor/Graphite/releases/download/latest-stable/graphite-self-hosted-build.zip
unzip ./graphite-self-hosted-build.zip
rm ./graphite-self-hosted-build.zip
mv graphite-* app # Rename' > update.sh

# Pull and start
chmod +x update.sh # Allow execute
./update.sh # Run the update script
docker compose up -d # Start container
```

Done, access on: `http://localhost:5656` and re-run the update script to get latest changes.

Note: The extracted folder in named something like `graphite-2025-01-09` so the script needs to work around that to a predictable name (like `/app`).

**Comment by redbeardymcgee** [comment]
I've added a podman quadlet [here](https://git.mcgee.red/redbeardymcgee/podbox/src/branch/main/quadlets/graphite-editor). It builds from the latest release artifact. I don't know if I'll add it to my container registry for now; not really sure how to keep it updated effectively yet. Restarting the container (`systemctl --user restart graphite-editor`) will rebuild it which includes downloading the release, and that's good enough for me right now.
