### ISSUE TITLE
Clicking on menu bar sub-menu entries doesn't work

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#280]
In `MenuList.vue`, the `@click="handleEntryClick(entry)"` is never called on sub-menu entries (such as *File* > *Open Recent*). It instead gets stuck in a state where it thinks we have a floating menu open.

**Comment by KeatonTech** [comment]
Problem lives in the rust InputPreprocessor: `The number of buttons modified at the same time was not equal to 1. Modification: 0b00000000`

**Comment by KeatonTech** [comment]
The root of the issue is that the submenu gets closed on mousedown, before it has a chance to have a full click. `FloatingMenu.isMouseEventOutsideFloatingMenu` is returning false for the child menu because `this.$refs.floatingMenuContent` is undefined (in fact, all refs are undefined). Still poking at it but it seems like the child menu never goes through the Vue lifecycle events and so is never 'created' even though the HTML is rendered.

**Comment by Keavon** [comment]
Thank you for poking around! This is a pretty important bug to iron out before the launch this month and it has so far flummoxed me in my attempts to debug it.
