### ISSUE TITLE
Preserve order on copy and paste

### ISSUE THREAD

**Issue by 0HyperCube** [GraphiteEditor/Graphite#610]
Currently the sort order of the layers is inverted when you copy and paste multiple layers. In the below example, the pasted text appears below the pasted gradient shape, whereas it should appear above.

![order](https://user-images.githubusercontent.com/78500760/164770789-882a7ee1-7f54-498a-9217-d6e66a482572.gif)

**Comment by Keavon** [comment]
Thanks for fixing this yesterday @nupsi! If you could just reply here so I can assign this issue to you, that'd help with organization since we normally assign issues to the people who work on them. And if you're on Discord, I'd also love to grant you the Code Contributor role, just let me know your username there. Cheers!

**Comment by nupsi** [comment]
Sounds good
