### ISSUE TITLE
When I open up the graphic editor on the web I get this mask paint error

### ISSUE THREAD

**Issue by ninjasaid2k** [GraphiteEditor/Graphite#872]
![errorthingy](https://user-images.githubusercontent.com/99513716/205125194-4ea6042b-3158-46ef-b050-1b3da68cd5ed.PNG)

what does this mean?

**Comment by 0HyperCube** [comment]
The editor automatically saves your work into your browser's database, so that if you restart the editor your old work can be shown again. However if the format used to save the the graphite document is different from the one being used to load it (due to an update to the editor) then loading the document may fail causing an error similar to this.

As the editor becomes more developed then we plan to stabilise the file format to avoid these breaking changes, however graphite is not yet developed enough to do this so you may unfortunately lose your work. I hope that answers you question @ninjasaid2k?
