### ISSUE TITLE
Fix boolean ops regression

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#931]
The boolean ops no longer works in most cases. It was never perfect, but now it rarely works except in ideal circumstances.

The current theory is that winding order has been incorrect since we switched away from Kurbo shapes.

Primitive shapes work with each other, and Pen tool shapes work with each other, but not between the two groups. That's why it's probably a winding order issue. Meaning this is potentially an easy fix.

**Comment by 0HyperCube** [comment]
I don't see why a different winding order would change anything? The algorithm goes around the two shapes looking for intersections, and then creates a new shape based on.

**Comment by 0HyperCube** [comment]
The direction of the user's path should dictate the winding order in my opinion, as it does in inkscape. Renderers will create triangles in the correct way for their graphics API. I believe that the boolean operation sometimes doesn't work on path tool shapes with strait edges due to the handles being located on top of the control points, rather than it just being a linear segment.
