### ISSUE TITLE
Fixed document size shouldn't allow scrolling/drawing outside

### ISSUE THREAD

**Issue by chrisyelf** [GraphiteEditor/Graphite#983]
Even though I chose a Document size (not infinite canvas), Graphite still lets me scroll infinitely and even draw outside the fixed size canvas. I think the ones choosing a size (like me) need to be constrained to that size. I can always change the Document size (I don't see how now, but I guess it is / should be possible).

**Comment by Keavon** [comment]
The area around artboards is called the pasteboard. It's a useful place to overhang or temporarily arrange current. However we do intend to dim the current outside the artboards, and let the user also choose to hide it entirely (equivalent to fully dimming it). The Layer Tree panel will also only display content belonging to the active artboard, or if no artboard is selected, it will display artboards and the pasteboard to choose from, thus giving content an owning artboard or pasteboard.

Feel free to continue the discussion but I'm going to close this issue since it's not the exact direction we intend to go when implementing further artboard and pasteboard functionality. Thanks for asking!
