### ISSUE TITLE
Group/ungroup selection of objects, on multiple levels

### ISSUE THREAD

**Issue by chrisyelf** [GraphiteEditor/Graphite#984]
I didn't see how to Group/ungroup selection of objects (on multiple levels). Is it possible?

Use case: Draw some objects which make a bigger object. Example from Excalidraw:
![Screenshot from 2023-01-21 16-24-20](https://user-images.githubusercontent.com/121562270/213871324-6c1bd70e-e2eb-4085-aaae-bffe2acc3ba4.png)
One can group these and then handle as a single object (move, resize, rotate...)
while editing individual objects in a group is still possible:
![Screenshot from 2023-01-21 16-24-52](https://user-images.githubusercontent.com/121562270/213871327-8b5c390d-8346-4091-a155-bfbafa392348.png)

Multiple levels: One could combine the stick man with another figure, and have that as a group, and so on.

**Comment by Keavon** [comment]
Hi, I'm trying to figure out precisely what you are referring to/asking/suggesting. Are you aware of the <kbd>Ctrl</kbd><kbd>G</kbd> (group) and <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>G</kbd> (ungroup) shortcuts? There is also the ability to drag layers into and out of groups in the Layer Tree panel. Is that an answer to the first part of your description? And then regarding the "multiple levels" part, I don't quite know what you mean by that. Could you record a video demo or spell out a series of steps where you perform a set of actions and point out where the behavior differs from what you expected/wanted? Thanks.

**Comment by chrisyelf** [comment]
Hi, thanks for looking into this.

> Are you aware of the CtrlG (group) and CtrlShiftG (ungroup) shortcuts?

I wasn't. That does group multiple items, I'm able to resize the group, but 

1. I can't drag the entire group
2. I can't get back to that selection after selecting something else

[Screencast from 2023-01-21 22-07-21.webm](https://user-images.githubusercontent.com/121562270/213885268-15544d6e-40b9-4402-b42e-49f3d15eab86.webm)

Desired behavior (from Excalidraw)

[Screencast from 2023-01-21 22-09-05.webm](https://user-images.githubusercontent.com/121562270/213885342-e31f0133-e82e-4233-93be-511dcb402544.webm)

Note how I can move entire group, then select something else, then come back to select the group.
One can select an individual item in group by double-clicking, working on it, and leaving and getting back to group:
[Screencast from 2023-01-21 22-11-25.webm](https://user-images.githubusercontent.com/121562270/213885437-d6763eba-8ae4-41c5-abbc-0df797940273.webm)

**Comment by Keavon** [comment]
Ok, so your goal is for the Select tool to select and manipulate groups not individual layers. And for double clicking something within that group to select the next shallowest child layer or group. That's been a feature I have been planning in my head but I haven't thought of filing an issue for it yet. I just did so now: #985

> 1. I can't drag the entire group

In the meantime, you can use the <kbd>G</kbd> shortcut (like in Blender) to move a selected group around.

> 2. I can't get back to that selection after selecting something else

You should be able to click the folder again in the Layer Tree panel. Or are you referring to some other multi-selection or something? I don't really understand you here.

Please let me know if there is something else not covered by that issue I filed. Closing this for now since I think that issue covers it, but I can potentially file others for you if I can grasp your other intentions. Thanks!

**Comment by chrisyelf** [comment]
Thanks!

**Comment by Keavon** [comment]
Sure thing, thanks for the suggestions and making me remember to actually file issues for things that need to be done! :)
